language: node_js 
node_js:
 - 6
docker:
 - docker1.12
refresh_token: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvQkk5SnhYd0VmLS0tT1VCYnlBM1Jja2IwOHV4U2dnMmxJaEZXem5MME1vIn0.eyJqdGkiOiJjMzJmNmIwNC0wOWZjLTQ4MWMtYWJiZi04ZmJiZTE1ZjM1ZDgiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNDkyNTY2MjUzLCJpc3MiOiJodHRwOi8vMTAuMTUzLjE5My4xMTQ6OTk5Ny9hdXRoL3JlYWxtcy9zaHV5dW4iLCJhdWQiOiJ1YXMiLCJzdWIiOiIxZGM4MDQwZi1hNjQyLTQwOWYtYTBmOC05ODVkNGM3NDU4MzEiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoidWFzIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiYzY2OGVjMmQtZmQ3NC00NDdkLTk4ZDQtMzkxZmRjOTUzZmY3IiwiY2xpZW50X3Nlc3Npb24iOiI2ZWJiNmE4MC0zZjJlLTRmYTctYjdhMi03ZTc5ZGIyZGI0ODIiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InVhcyI6eyJyb2xlcyI6WyJEZXZlbG9wZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJ2aWV3LXByb2ZpbGUiXX19fQ.MGx-ftVQ6z4ax2IHRkGI0W9UW5g880MSU_ChvlSQq-p3NqryNr8zElV3Lq4HGLrWS7hDaHwto4Orvf-QgQxv7CeHR4dn4CjBrNNdZx2ZlkdAM7Sdta98_HlEVap4j5SHhMQ8XnogJ6fzC25bOhX7rV3s09Z1aerXd6l02AC9FeSDzTRKF0V447odldDNL0mww4N1I2i1GIolItcyDzoBPhKmstUFK3ZFOkwGmQd18yVlzVcLdJd3PmKiZ1AoAMrS1dwPT9Q-HXb86p55UIKWEt3b3VxMAVV8fbIdIhziUHclo7zRnhPTeHKHWly3oi4tQjJzlr-19Si9C7de0SmyOQ
build:
 script:
  - npm-cache install --registry=https://registry.npm.taobao.org
  - npm run dist 
 app_version: "1.0"
package:
 - type: docker
   docker_file: Dockerfile
   registry_uri: hub.fenxibao.com
   image_name: basecrm/campagin-fe
   image_tag: ${APP_VERSION}-${TIMESTAMP}
compose:
 - type: service
   service_file: .service.yml
