module.exports = [{
    "valueShow": "基本信息",
    "category_type_id": 1,
    "queryItemRequestNewList": [{
        "id": "queryitem:130",
        "valueId": 130,
        "name": "数字输入",
        "type": "数字输入",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:124",
        "valueId": 124,
        "name": "字符输入",
        "type": "字符输入",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:125",
        "valueId": 125,
        "name": "日期选择",
        "type": "日期选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:12000",
        "valueId": 12000,
        "name": "生日选择",
        "type": "生日选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:12000",
        "valueId": 12000,
        "name": "生日选择",
        "type": "生日选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:126",
        "valueId": 126,
        "name": "时间选择",
        "type": "时间选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:127",
        "valueId": 127,
        "name": "字典选择",
        "type": "字典选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:19000",
        "valueId": 19000,
        "name": "标签选择",
        "type": "标签选择",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:1504",
        "valueId": 1504,
        "name": "外部数据导入",
        "type": "外部数据导入",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:128",
        "valueId": 128,
        "name": "关键字定制",
        "type": "关键字定制",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:111",
        "valueId": 111,
        "name": "店铺",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:222",
        "valueId": 222,
        "name": "开卡城市",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:333",
        "valueId": 333,
        "name": "开卡大区",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    },
    {
        "id": "queryitem:111",
        "valueId": 111,
        "name": "Usual Store",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:222",
        "valueId": 222,
        "name": "Usual Store Region",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    }, {
        "id": "queryitem:333",
        "valueId": 333,
        "name": "Product Model",
        "type": "数据选择器类型",
        "valueShow": "基本信息"
    },
    {
      "id": "queryitem:111",
      "valueId": 111,
      "name": "地区选择",
      "type": "地区选择",
      "valueShow": "基本信息"
    }],
    "conditionNewList": null
}, {
    "valueShow": "自定义属性",
    "category_type_id": 5,
    "queryItemRequestNewList": [{
        "id": "queryitem:60161",
        "valueId": 60161,
        "name": "字符选择1216001",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70146",
        "valueId": 70146,
        "name": "选一个",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70405",
        "valueId": 70405,
        "name": "我是字符输入",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70151",
        "valueId": 70151,
        "name": "哈妹特吞吞吐吐",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70410",
        "valueId": 70410,
        "name": "我是数字选择111",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60171",
        "valueId": 60171,
        "name": "数字选择1216001",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70415",
        "valueId": 70415,
        "name": "我是字符选择",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60176",
        "valueId": 60176,
        "name": "数字输入1216001",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70161",
        "valueId": 70161,
        "name": "陈素梅test1",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70420",
        "valueId": 70420,
        "name": "我是数字输入",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60181",
        "valueId": 60181,
        "name": "日期输入1216001",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70166",
        "valueId": 70166,
        "name": "陈素梅test2",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70425",
        "valueId": 70425,
        "name": "我是日期选择",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70171",
        "valueId": 70171,
        "name": "陈素梅test3",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60191",
        "valueId": 60191,
        "name": "字符输入20150113",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70176",
        "valueId": 70176,
        "name": "陈素梅test4",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60196",
        "valueId": 60196,
        "name": "test123",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70181",
        "valueId": 70181,
        "name": "陈素梅test5",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60201",
        "valueId": 60201,
        "name": "20150210自定义属性",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70186",
        "valueId": 70186,
        "name": "WYY2015120083",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60206",
        "valueId": 60206,
        "name": "20150210字符输入",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70191",
        "valueId": 70191,
        "name": "自定义属性字符输入",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60211",
        "valueId": 60211,
        "name": "日期选择10150210",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60216",
        "valueId": 60216,
        "name": "肤质",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70208",
        "valueId": 70208,
        "name": "啊啊啊啊啊啊啊啊",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60224",
        "valueId": 60224,
        "name": "IUOU",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60229",
        "valueId": 60229,
        "name": "肤质1",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60234",
        "valueId": 60234,
        "name": "字符选择0528",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70223",
        "valueId": 70223,
        "name": "来来选一个",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70228",
        "valueId": 70228,
        "name": "放放放",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70243",
        "valueId": 70243,
        "name": "阿斯达",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70248",
        "valueId": 70248,
        "name": "是是是",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70253",
        "valueId": 70253,
        "name": "aasss",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70258",
        "valueId": 70258,
        "name": "xinxin",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70263",
        "valueId": 70263,
        "name": "数字输入数字输入数字输入数字输入数字输入",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60279",
        "valueId": 60279,
        "name": "sale",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70011",
        "valueId": 70011,
        "name": "yy",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70268",
        "valueId": 70268,
        "name": "怡宝",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60284",
        "valueId": 60284,
        "name": "xxx",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70016",
        "valueId": 70016,
        "name": "jd",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70273",
        "valueId": 70273,
        "name": "漫步者呃",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70021",
        "valueId": 70021,
        "name": "dd",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70278",
        "valueId": 70278,
        "name": "4444任",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70026",
        "valueId": 70026,
        "name": "yhd",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70283",
        "valueId": 70283,
        "name": "字符输入1",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70031",
        "valueId": 70031,
        "name": "pp",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70288",
        "valueId": 70288,
        "name": "字符选择1",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70293",
        "valueId": 70293,
        "name": "数字输入1",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70298",
        "valueId": 70298,
        "name": "数字选择1",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60316",
        "valueId": 60316,
        "name": "按时发大厦",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70303",
        "valueId": 70303,
        "name": "日期选择1",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60321",
        "valueId": 60321,
        "name": "阿萨德发",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70308",
        "valueId": 70308,
        "name": "字符选择2",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60326",
        "valueId": 60326,
        "name": "苟富贵",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60071",
        "valueId": 60071,
        "name": "数字选择1030003",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70313",
        "valueId": 70313,
        "name": "字符输入2",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60076",
        "valueId": 60076,
        "name": "字符选择1030003",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70318",
        "valueId": 70318,
        "name": "我是自定义名称123我是自定义名称123",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60081",
        "valueId": 60081,
        "name": "字符输入1030003",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70323",
        "valueId": 70323,
        "name": "字符输入22",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70328",
        "valueId": 70328,
        "name": "数字输入22",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70073",
        "valueId": 70073,
        "name": "第一个自定义属",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60091",
        "valueId": 60091,
        "name": "日期选择1030003",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70333",
        "valueId": 70333,
        "name": "日期选择22",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70078",
        "valueId": 70078,
        "name": "zzzzz",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60096",
        "valueId": 60096,
        "name": "日期选择1030004",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70338",
        "valueId": 70338,
        "name": "字符选择22",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70083",
        "valueId": 70083,
        "name": "自定义属性数字选择",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60101",
        "valueId": 60101,
        "name": "数字输入1030004",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70343",
        "valueId": 70343,
        "name": "数字选择22",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70348",
        "valueId": 70348,
        "name": "就好撒更好地手感",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70353",
        "valueId": 70353,
        "name": "222",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60116",
        "valueId": 60116,
        "name": "字符选择20141202",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70101",
        "valueId": 70101,
        "name": "新的自定义属性",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70358",
        "valueId": 70358,
        "name": "hame",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60121",
        "valueId": 60121,
        "name": "我是日期选择20141202",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70106",
        "valueId": 70106,
        "name": "自定义数字",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70363",
        "valueId": 70363,
        "name": "test223232322",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60126",
        "valueId": 60126,
        "name": "字符选择1203001",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70111",
        "valueId": 70111,
        "name": "AutoTest",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70368",
        "valueId": 70368,
        "name": "222cdddd",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60131",
        "valueId": 60131,
        "name": "字符输入1203001",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70373",
        "valueId": 70373,
        "name": "2322",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60136",
        "valueId": 60136,
        "name": "数字选择1203001",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70121",
        "valueId": 70121,
        "name": "字符选择",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70378",
        "valueId": 70378,
        "name": "23323232",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60141",
        "valueId": 60141,
        "name": "数字输入1203001",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70126",
        "valueId": 70126,
        "name": "字符输入",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70383",
        "valueId": 70383,
        "name": "88",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60146",
        "valueId": 60146,
        "name": "日期选择1203001",
        "type": "日期选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70131",
        "valueId": 70131,
        "name": "数字选择",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70388",
        "valueId": 70388,
        "name": "999",
        "type": "字典选择",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70136",
        "valueId": 70136,
        "name": "数字输入",
        "type": "数字输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:70393",
        "valueId": 70393,
        "name": "自定义",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }, {
        "id": "queryitem:60156",
        "valueId": 60156,
        "name": "商品人群划分",
        "type": "字符输入",
        "valueShow": "自定义属性"
    }],
    "conditionNewList": null
}, {
    "valueShow": "千牛插件标签",
    "category_type_id": 1,
    "queryItemRequestNewList": [],
    "conditionNewList": [{
        "attributeId": null,
        "attributeType": null,
        "orderId": 1,
        "conditionValueList": [{
            "dicId": 7013,
            "displayName": "tomwalk",
            "displayValue": null,
            "parentValue": null
        }]
    }]
}, {
    "valueShow": "千牛自定义属性",
    "category_type_id": 1,
    "queryItemRequestNewList": [],
    "conditionNewList": [{
        "attributeId": null,
        "attributeType": null,
        "orderId": 1,
        "conditionValueList": [{
            "dicId": 6502,
            "displayName": "miaomiaozhu0620",
            "displayValue": null,
            "parentValue": null
        }, {
            "dicId": 7011,
            "displayName": "j恶魔无敌",
            "displayValue": null,
            "parentValue": null
        }, {
            "dicId": 7012,
            "displayName": "shendawei2012",
            "displayValue": null,
            "parentValue": null
        }, {
            "dicId": 7016,
            "displayName": "大狗子19890202",
            "displayValue": null,
            "parentValue": null
        }]
    }]
}, {
    "valueShow": "会员卡",
    "category_type_id": 2,
    "queryItemRequestNewList": [{
        "id": "queryitem:70000",
        "valueId": 70000,
        "name": "等级生效日期",
        "type": "日期选择",
        "valueShow": "会员卡"
    }, {
        "id": "queryitem:70001",
        "valueId": 70001,
        "name": "等级失效日期",
        "type": "日期选择",
        "valueShow": "会员卡"
    }, {
        "id": "queryitem:70002",
        "valueId": 70002,
        "name": "当前积分",
        "type": "数字输入",
        "valueShow": "会员卡"
    }, {
        "id": "queryitem:70010",
        "valueId": 70010,
        "name": "邮件订阅",
        "type": "字典选择",
        "valueShow": "会员卡"
    }, {
        "id": "queryitem:70006",
        "valueId": 70006,
        "name": "即将到期积分",
        "type": "即将到期积分",
        "valueShow": "会员卡"
    }],
    "conditionNewList": [{
        "attributeId": 19100,
        "attributeType": "normal",
        "orderId": 1,
        "conditionValueList": [{
            "dicId": 210,
            "displayName": "大狗子19890202",
            "displayValue": "69",
            "parentValue": null
        }, {
            "dicId": 210,
            "displayName": "miaomiaozhu0620卡",
            "displayValue": "5",
            "parentValue": null
        }, {
            "dicId": 210,
            "displayName": "tomwalk卡",
            "displayValue": "201",
            "parentValue": null
        }]
    }]
}, {
    "valueShow": "店铺会员等级",
    "category_type_id": 2,
    "queryItemRequestNewList": [{
        "id": "queryitem:1203",
        "valueId": 1203,
        "name": "会员等级",
        "type": "字典选择",
        "valueShow": "店铺会员等级"
    }],
    "conditionNewList": [{
        "attributeId": 1200,
        "attributeType": "normal",
        "orderId": 1,
        "conditionValueList": [{
            "dicId": 10,
            "displayName": "yy",
            "displayValue": "100000",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "j恶魔无敌",
            "displayValue": "100094062",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "大狗子19890202",
            "displayValue": "100571094",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "数云小产品",
            "displayValue": "101854160",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "数云食堂",
            "displayValue": "106878997",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "perttyhui_lover",
            "displayValue": "108243594",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "淘宝测试店",
            "displayValue": "109221313",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "michaelchan0924",
            "displayValue": "113721306",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "emilyty10433",
            "displayValue": "128611773",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "0黑色的琴键0",
            "displayValue": "157263193",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "小嘴儿90",
            "displayValue": "162405652",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "茵曼旗舰店",
            "displayValue": "57301243",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "tomwalk",
            "displayValue": "65927470",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "lerous",
            "displayValue": "69988687",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "miaomiaozhu0620",
            "displayValue": "71677914",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "桔熊服饰旗舰店",
            "displayValue": "72261298",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "shendawei2012",
            "displayValue": "72274236",
            "parentValue": null
        }]
    }]
}, {
    "valueShow": "RFM模型",
    "category_type_id": 2,
    "queryItemRequestNewList": [{
        "id": "queryitem:9004",
        "valueId": 9004,
        "name": "购买次数",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9005",
        "valueId": 9005,
        "name": "购买订单数",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9006",
        "valueId": 9006,
        "name": "购买金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9007",
        "valueId": 9007,
        "name": "购买件数",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9008",
        "valueId": 9008,
        "name": "退款次数",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9009",
        "valueId": 9009,
        "name": "退款金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9010",
        "valueId": 9010,
        "name": "最后一次购买时间",
        "type": "日期选择",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9011",
        "valueId": 9011,
        "name": "最后一次购买金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9012",
        "valueId": 9012,
        "name": "最后一次购买间隔",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9013",
        "valueId": 9013,
        "name": "第一次购买时间",
        "type": "日期选择",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9014",
        "valueId": 9014,
        "name": "第一次购买金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9015",
        "valueId": 9015,
        "name": "第一次购买间隔",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9016",
        "valueId": 9016,
        "name": "平均每次购买金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9017",
        "valueId": 9017,
        "name": "平均每次购买件数",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9018",
        "valueId": 9018,
        "name": "平均每次购买间隔",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9019",
        "valueId": 9019,
        "name": "平均发货到确认收货间隔",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9020",
        "valueId": 9020,
        "name": "最大单笔订单购买金额",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9021",
        "valueId": 9021,
        "name": "订单级优惠费用",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }, {
        "id": "queryitem:9022",
        "valueId": 9022,
        "name": "商品级优惠费用",
        "type": "数字输入",
        "valueShow": "RFM模型"
    }],
    "conditionNewList": [{
        "attributeId": 1301,
        "attributeType": "normal",
        "orderId": 1,
        "conditionValueList": [{
            "dicId": 10,
            "displayName": "yy",
            "displayValue": "100000",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "j恶魔无敌",
            "displayValue": "100094062",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "大狗子19890202",
            "displayValue": "100571094",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "数云小产品",
            "displayValue": "101854160",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "数云食堂",
            "displayValue": "106878997",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "perttyhui_lover",
            "displayValue": "108243594",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "淘宝测试店",
            "displayValue": "109221313",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "michaelchan0924",
            "displayValue": "113721306",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "emilyty10433",
            "displayValue": "128611773",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "0黑色的琴键0",
            "displayValue": "157263193",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "小嘴儿90",
            "displayValue": "162405652",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "茵曼旗舰店",
            "displayValue": "57301243",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "tomwalk",
            "displayValue": "65927470",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "lerous",
            "displayValue": "69988687",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "miaomiaozhu0620",
            "displayValue": "71677914",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "桔熊服饰旗舰店",
            "displayValue": "72261298",
            "parentValue": null
        }, {
            "dicId": 10,
            "displayName": "shendawei2012",
            "displayValue": "72274236",
            "parentValue": null
        }]
    }, {
        "attributeId": 1302,
        "attributeType": "normal",
        "orderId": 2,
        "conditionValueList": [{
            "dicId": 11,
            "displayName": "时间不限",
            "displayValue": "6",
            "parentValue": null
        }, {
            "dicId": 11,
            "displayName": "最近30天",
            "displayValue": "1",
            "parentValue": null
        }, {
            "dicId": 11,
            "displayName": "最近60天",
            "displayValue": "2",
            "parentValue": null
        }, {
            "dicId": 11,
            "displayName": "最近90天",
            "displayValue": "3",
            "parentValue": null
        }, {
            "dicId": 11,
            "displayName": "最近180天",
            "displayValue": "4",
            "parentValue": null
        }, {
            "dicId": 11,
            "displayName": "最近1年",
            "displayValue": "5",
            "parentValue": null
        }]
    }]
}, {
    "valueShow": "RFM",
    "category_type_id": 2,
    "queryItemRequestNewList": [
        {
            "id": "queryitem:456891041",
            "valueId": 456891041,
            "name": "Purchase Amount (30 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": 3
        },
        {
            "id": "queryitem:371003588",
            "valueId": 371003588,
            "name": "Purchase Amount (60 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:285116135",
            "valueId": 285116135,
            "name": "Purchase Amount (90 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1422316277",
            "valueId": 1422316277,
            "name": "Purchase Amount (180 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:401232227",
            "valueId": 401232227,
            "name": "Purchase Amount (1 Year)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:401152759",
            "valueId": 401152759,
            "name": "Purchase Amount (Ever)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:539916492",
            "valueId": 539916492,
            "name": "Purchase Quantity (30 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:625803945",
            "valueId": 625803945,
            "name": "Purchase Quantity (60 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:711691398",
            "valueId": 711691398,
            "name": "Purchase Quantity (90 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:2036388568",
            "valueId": 2036388568,
            "name": "Purchase Quantity (180 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1818860630",
            "valueId": 1818860630,
            "name": "Purchase Quantity (1 Year)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:198766518",
            "valueId": 198766518,
            "name": "Purchase Quantity (Ever)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:750536869",
            "valueId": 750536869,
            "name": "Avg Bskt Amount (30 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:836424322",
            "valueId": 836424322,
            "name": "Avg Bskt Amount (60 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:197875823",
            "valueId": 197875823,
            "name": "Avg Bskt Amount (180 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:922311775",
            "valueId": 922311775,
            "name": "Avg Bskt Amount (90 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1083839139",
            "valueId": 1083839139,
            "name": "Avg Bskt Amount (1 Year)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1629151695",
            "valueId": 1629151695,
            "name": "Avg Bskt Amount (Ever)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:2050493215",
            "valueId": 2050493215,
            "name": "Avg Purchase Interval (30 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:2136380668",
            "valueId": 2136380668,
            "name": "Avg Purchase Interval (60 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1841816885",
            "valueId": 1841816885,
            "name": "Avg Purchase Interval (180 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:2072699175",
            "valueId": 2072699175,
            "name": "Avg Purchase Interval (90 Days)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1451946915",
            "valueId": 1451946915,
            "name": "Avg Purchase Interval (1 Year)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1572403913",
            "valueId": 1572403913,
            "name": "Avg Purchase Interval (Ever)",
            "type": "数字输入",
            "valueShow": "RFM",
            "dicType": null
        },
        {
            "id": "queryitem:1992912229",
            "valueId": 1992912229,
            "name": "Last Purchase Date",
            "type": "时间选择",
            "valueShow": "RFM",
            "dicType": null
        }
    ],
    "conditionNewList": [
        {
            "attributeId": "",
            "attributeType": "",
            "orderId": 1,
            "conditionValueList": [
                {
                    "dicId": 8821,
                    "displayName": "Avg Bskt Amount",
                    "displayValue": "",
                    "parentValue": null,
                    "dicType": "1"
                },
                {
                    "dicId": 8821,
                    "displayName": "Avg Purchase Interval",
                    "displayValue": "",
                    "parentValue": null,
                    "dicType": "2"
                },
                {
                    "dicId": 8821,
                    "displayName": "Purchase Amount",
                    "displayValue": "",
                    "parentValue": null,
                    "dicType": "3"
                },
                {
                    "dicId": 8821,
                    "displayName": "Purchase Quantity",
                    "displayValue": "",
                    "parentValue": null,
                    "dicType": "4"
                }
            ]
        }
    ]
}]
